version: "3"

networks:
   sample-project-net:
    ipam:
      config:
        - subnet: 172.20.1.0/24
volumes:
    sample-project-cache-volume : {}
    sample-project-media-volume : {}
services:
    sample-project-cache:
      image: redis:6.2.6-alpine
      command: redis-server --requirepass samplepassword --port 6379
      ports:
        - "127.0.0.1:6379:6379"
      healthcheck:
        test: "redis-cli -h 127.0.0.1 ping"
        interval: 3s
        timeout: 1s
        retries: 5
      networks:
        sample-project-net:
          ipv4_address: 172.20.1.3
    sample-project:
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - "127.0.0.1:8000:8000"
      depends_on:
        - sample-project-cache
      links:
        - sample-project-cache:sample-project-cache
      command: bash -c "pip3 install -r requirements.txt && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
      networks:
        sample-project-net:
          ipv4_address: 172.20.1.4

